config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'

  devise_for :managers, controllers: {
    sessions: 'managers/sessions'
  }

  resources :end_shifts
  
  devise_for :cashiers, controllers: {
    sessions: 'cashiers/sessions'
  }
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'    
  }
  
  resources :consumptions
  resources :supplies  do
    collection do
      put :directUpdate
    end    
  end
  resources :order_details
  
  resources :orders do
    collection do
      put :update_supplies
    end    
  end
  resources :products
  resources :categories

end

app/models/end_shift.rb
class EndShift < ActiveRecord::Base

	def createShift(cash)
		#EndShift.create(cashier_name: 'Nachin', cash: cash)
		self.cashier_name = 'Nachin'
		self.cash = cash
	end
end

app/controllers/end_shifts_controller.rb
class EndShiftsController < ApplicationController
  before_action :set_end_shift, only: [:show, :edit, :update, :destroy]
  
  def index
    @end_shifts = EndShift.all
  end

  def show
  end

  def new
    @end_shift = EndShift.new

    @cashier_name = params[:cashier_name]
    @total_cash = params[:total_cash]
    @total_credit = params[:total_credit]
    @total_debit = params[:total_debit]
    @total_agreement = params[:total_agreement]
  end

  def edit
  end

  def create
    @end_shift = EndShift.new(end_shift_params)
    
    respond_to do |format|
      if @end_shift.save
        format.html { redirect_to root_path, notice: 'End shift was successfully created.' }
        format.json { render :show, status: :created, location: @end_shift }
      else
        format.html { render :new }
        format.json { render json: @end_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @end_shift.update(end_shift_params)
        format.html { redirect_to @end_shift, notice: 'End shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @end_shift }
      else
        format.html { render :edit }
        format.json { render json: @end_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @end_shift.destroy
    respond_to do |format|
      format.html { redirect_to end_shifts_url, notice: 'End shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_end_shift
      @end_shift = EndShift.find(params[:id])
    end

    def end_shift_params
      params.require(:end_shift).permit(:cashier_name, :cash, :debit, :credit, :agreement)
    end
end

app/helpers/end_shifts_helper.rb
module EndShiftsHelper
end

app/views/end_shifts/_form.html.erb
<%= form_for(@end_shift) do |f| %>
  <% if @end_shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@end_shift.errors.count, "error") %> prohibited this end_shift from being saved:</h2>

      <ul>
      <% @end_shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cashier_name %><br>
    <%= f.text_field :cashier_name, :value => @cashier_name, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :cash %><br>
    <%= f.number_field :cash, :value => @total_cash, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :debit %><br>
    <%= f.number_field :debit, :value => @total_debit, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.number_field :credit, :value => @total_credit, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :agreement %><br>
    <%= f.number_field :agreement, :value => @total_agreement, :readonly => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/end_shifts/edit.html.erb
<h1>Editing End Shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @end_shift %> |
<%= link_to 'Back', end_shifts_path %>

app/views/end_shifts/index.html.erb
<section class="end-shifts">
  <p id="notice"><%= notice %></p>

  <h1>Listing End Shifts</h1>

  <div class="table-wrapper">
    <table>
      <thead>
        <tr>
          <th>Cashier name</th>
          <th>Cash</th>
          <th>Debit</th>
          <th>Credit</th>
          <th>Agreement</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @end_shifts.each do |end_shift| %>
          <tr class="table-row">
            <td><%= end_shift.cashier_name %></td>
            <td><%= end_shift.cash %></td>
            <td><%= end_shift.debit %></td>
            <td><%= end_shift.credit %></td>
            <td><%= end_shift.agreement %></td>
            <td><%= link_to 'Show', end_shift %></td>

            <% if manager_signed_in? %>
            <td><%= link_to 'Edit', edit_end_shift_path(end_shift) %></td>
            <td><%= link_to 'Destroy', end_shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>  
  </div>
  
  <br>

  <%= link_to 'New End shift', new_end_shift_path %>  
</section>

app/views/end_shifts/new.html.erb
<section class="end-shift-new">
	<h1>Confirmar cierre de Caja</h1>
	<p><%= @cashier_name %></p>
	<%= render 'form' %>



	<%= link_to 'Back', end_shifts_path %>	
</section>

app/views/end_shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cashier name:</strong>
  <%= @end_shift.cashier_name %>
</p>

<p>
  <strong>Cash:</strong>
  <%= @end_shift.cash %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @end_shift.debit %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @end_shift.credit %>
</p>

<p>
  <strong>Agreement:</strong>
  <%= @end_shift.agreement %>
</p>

<%= link_to 'Edit', edit_end_shift_path(@end_shift) %> |
<%= link_to 'Back', end_shifts_path %>