config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'

  devise_for :managers, controllers: {
    sessions: 'managers/sessions'
  }

  resources :end_shifts
  
  devise_for :cashiers, controllers: {
    sessions: 'cashiers/sessions'
  }
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'    
  }
  
  resources :consumptions
  resources :supplies  do
    collection do
      put :directUpdate
    end    
  end
  resources :order_details
  
  resources :orders do
    collection do
      put :update_supplies
    end    
  end
  resources :products
  resources :categories

end

app/models/supply.rb
class Supply < ActiveRecord::Base
	has_many :consumptions
	
	has_many :products, through: :consumptions

end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_manager!
  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def directUpdate
    #Supply.where(:id params[:supply_ids]).update_all({name: 'Back'})
    Supply.where(id: params[:supply_id]).update_all(name: 'Nuggest')

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.require(:supply).permit(:name, :stock)
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_for(@supply) do |f| %>
  <% if @supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supply.errors.count, "error") %> prohibited this supply from being saved:</h2>

      <ul>
      <% @supply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/supplies/edit.html.erb
<h1>Editing Supply</h1>

<%= render 'form' %>

<%= link_to 'Show', @supply %> |
<%= link_to 'Back', supplies_path %>

app/views/supplies/index.html.erb
<section class="supplies">
  <p id="notice"><%= notice %></p>

  <h1>Insumos</h1>

  <%= form_tag directUpdate_supplies_path, method: :put do %>

  <div class="table-wrapper">
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Stock</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @supplies.each do |supply| %>
          <tr class="table-row">
            <td><%= supply.id %></td>
            <td><%= supply.name %></td>
            <td><%= supply.stock %></td>
            <td><%= link_to 'Show', supply %></td>
            <td><%= link_to 'Edit', edit_supply_path(supply) %></td>
            <td><%= link_to 'Destroy', supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>  
  </div>
  
    <%= submit_tag %>
  <% end %>
  <br>

  <%= link_to 'New Supply', new_supply_path %>  
</section>

app/views/supplies/new.html.erb
<h1>New Supply</h1>

<%= render 'form' %>

<%= link_to 'Back', supplies_path %>

app/views/supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supply.name %>
</p>

<%= link_to 'Edit', edit_supply_path(@supply) %> |
<%= link_to 'Back', supplies_path %>