config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'

  devise_for :managers, controllers: {
    sessions: 'managers/sessions'
  }

  resources :end_shifts
  
  devise_for :cashiers, controllers: {
    sessions: 'cashiers/sessions'
  }
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'    
  }
  
  resources :consumptions
  resources :supplies  do
    collection do
      put :directUpdate
    end    
  end
  resources :order_details
  
  resources :orders do
    collection do
      put :update_supplies
    end    
  end
  resources :products
  resources :categories

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cashier.rb
class Cashier < ActiveRecord::Base
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/consumption.rb
class Consumption < ActiveRecord::Base
	belongs_to :product
	belongs_to :supply
end

app/models/end_shift.rb
class EndShift < ActiveRecord::Base

	def createShift(cash)
		#EndShift.create(cashier_name: 'Nachin', cash: cash)
		self.cashier_name = 'Nachin'
		self.cash = cash
	end
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_details
	belongs_to :cashier
	accepts_nested_attributes_for :order_details

	
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
	belongs_to :product
	belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_many :order_details
	has_many :consumptions
	has_many :supplies, through: :consumptions

	accepts_nested_attributes_for :consumptions, allow_destroy: true
end

app/models/supply.rb
class Supply < ActiveRecord::Base
	has_many :consumptions
	
	has_many :products, through: :consumptions

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/consumptions_helper.rb
module ConsumptionsHelper
end

app/helpers/end_shifts_helper.rb
module EndShiftsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_header.html.erb
<header>
	<nav>
		<ul>
		<% if manager_signed_in? %>			
			<li><%= link_to "Productos", products_path %></li>
			<li><%= link_to "Insumos", supplies_path %></li>
			<li><%= link_to "Categorias", categories_path %></li>
			<li><%= link_to "Ventas", orders_path %></li>			
			<li><%= link_to "Cerrar Manager", destroy_manager_session_path, method: :delete %></li>			

		<% elsif admin_signed_in? %>
			<%#= link_to "Cerrar Admin", destroy_admin_session_path, method: :delete %>
		<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>LaPapitaPro</title>
  
	<script type="text/javascript" src="/assets/rsvp-3.1.0.min.js"></script>
	<script type="text/javascript" src="/assets/sha-256.min.js"></script>
	<script type="text/javascript" src="/assets/qz-tray.js"></script>
	
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', params[:controller] %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>