config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'

  devise_for :managers, controllers: {
    sessions: 'managers/sessions'
  }

  resources :end_shifts
  
  devise_for :cashiers, controllers: {
    sessions: 'cashiers/sessions'
  }
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'    
  }
  
  resources :consumptions
  resources :supplies  do
    collection do
      put :directUpdate
    end    
  end
  resources :order_details
  
  resources :orders do
    collection do
      put :update_supplies
    end    
  end
  resources :products
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_manager!
  def index
    @categories = Category.all
  end

  
  def show
  end

  
  def new
    @category = Category.new
  end

  
  def edit
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, remote: true do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<section class="categories">
  <p id="notice"><%= notice %></p>

  <h1>Listing categories</h1>

  <div class="table-wrapper">
    <table>
      <thead>
        <tr>
          <th>category name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr class="table-row">
            <td><%= category.name %></td>
            <td><%= link_to 'Show', category %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>  
  </div>

  <br>

  <%= link_to 'New category', new_category_path %>  
</section>

app/views/categories/new.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Detail:</strong>
  <%= @category.name %>
</p>

<%= link_to 'New Category', new_category_path %>
<%= link_to 'Edit', edit_order_path(@category) %> |
<%= link_to 'Back', orders_path %>